{% set name = "cogapp" %}
{% set version = "2.5.1" %}
{% set sha256 = "f8cf2288fb5a2087eb4a00d8b347ddc86e9058d4ab26b8c868433eb401adfe1c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - cogapp

about:
  home: http://nedbatchelder.com/code/cog
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Cog: A code generator for executing Python snippets in source files.'

  description: |
    Cog is a file generation tool. It lets you use pieces of Python
    code as generators in your source files to generate whatever text
    you need.
  doc_url: http://nedbatchelder.com/code/cog
  dev_url: https://bitbucket.org/ned/cog

extra:
  recipe-maintainers:
    - johannesring
    - edisongustavo
    - kghustad
