{% set name = "cogapp" %}
{% set version = "3.3.0" %}
{% set sha256 = "1be95183f70282422d594fa42426be6923070a4bd8335621f6347f3aeee81db0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - cogapp

about:
  home: http://nedbatchelder.com/code/cog
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Cog: A code generator for executing Python snippets in source files.'

  description: |
    Cog is a file generation tool. It lets you use pieces of Python
    code as generators in your source files to generate whatever text
    you need.
  doc_url: http://nedbatchelder.com/code/cog
  dev_url: https://bitbucket.org/ned/cog

extra:
  recipe-maintainers:
    - johannesring
    - edisongustavo
    - kghustad
