travis:
  secure:
    BINSTAR_TOKEN: B9RkbLvh+yZLXVuYuiOk/dRIk9yb1K+GH0/LIWD7NbaK/f555A+VTSCpkbEm9F4WgjAZ2nBtsSYn9jM5arbxvJ3IM6yI6PtNE3QTCGwLJetDOZSttHzglMb0+lDS0AFntEXaxdZIDMbDzMU7smWsIVmAVwdUyqsFa7CZ7wxRWyn2/CXrka89N+T4XR4Roly6ahUuZyiFssmIE0n/gpCZmd9fyvfuTR7bviT5uf1F7gm039WBsmC1wBIMkhmV/z7MqI9vMS2eOLvvTEwQr5MDmfy9vvEab48XgqnvvGoh3ji0iB2Scqchc/FhqM15SHgMFA0L7dOrio2IGuvai7YdkF8JqzKUjGbsfY/YGkMekRTqcQI020rTdEKmBlkQ+zsaPksHbcGiE+lTpKiCB8OI3eX12z0JgmL/HdHmUTEPPsWESvVh+qxPP0WyqSBYFfzvqNf3mP0M8iD6C+mL+QxlYoFvuverdw4MH6VYSs1NTYTGIQiRtW4rujK+sy0g4m4QOSP7yR9IbD/DXNaiBgoKz7rPmCoxFkFR16wZo4hyLVSB/fQAItDKHCN1R4v9pWnX+GdPeRKLauwq3KKJIeGEEFZkv8tAgShVeISxBvejAYF72n8dYmNYUjdY8OqJZN7Hc5muJLLEtR6G1fdMiIsgLUxa5NngMSNG3n1H7z/krCw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
