appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: wrLxWjl9FCDFmI1Xu2pMjjWh3WR/QrZ+LMCrPkxM8WlKBDrtaV0cySueztEa9PthmxryMqJa/4pff5QQAjilALWdHzLzgHNlF4FGpjKfGoYk5qPFgdP/Xs/29xWKI/gN1ZfFOuf8/f626jF6IltNqC4QFaa/FAVEGNDCrF10p6xzTjdv2zhgmC32GRNYaG+Nedy27QLV11su0ZMns3uGz1qAolAAy4wzWeiKYK8KaMfSaYf8jUTXnOKY5E0Fvw14vN64sIPpflpwks4AWz70EuUFVLESVgHSinZn3XfArYwkZlmfZHHHhbKhEWfpmVHOfxHq/EvUhPkkNJflGEI0+PHtPmydZJXda5XJGf0Viz8sedScVkAniDQduP7zHizy0hRZcce7mc0zYzO7DWyw0l7rE7P12QNsZ90qJxxt9JzidmwJp2eRGYp768PJZDW6j3190a0scsQhusRgPlWOS58b01HFlG0sM6vtAX10SxSad0PNcfvb/JseXbA4HX6WxtuKQFWAIXa1JOk+S+xSCidiNcM+bnx7h+crAFXb1q27k7QgDnZE1KrM4fln5UOOANqu3+pyFxielgHdL/l/IF9Hcoffp5LpUsPdSrag81ibLTFyPPtE2OgVdtyumFbzlW1I4dHcsOCl3/IEo0i6fcvxtivWLSRi7V0Iq1cb/Wg=}
provider:
  win: azure
conda_forge_output_validation: true
